# Generated by Django 6.0.3 on 2026-07-12 07:55

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Товар (Код)', 'verbose_name_plural': 'Товары (Код)'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='demo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Live Demo'),
        ),
        migrations.AddField(
            model_name='product',
            name='doc_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на документацию'),
        ),
        migrations.AddField(
            model_name='product',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступен для покупки'),
        ),
        migrations.AddField(
            model_name='product',
            name='license_type',
            field=models.CharField(choices=[('mit', 'MIT License'), ('gpl', 'GPL v3'), ('apache', 'Apache 2.0'), ('commercial_regular', 'Коммерческая (Обычная)'), ('commercial_extended', 'Коммерческая (Расширенная)')], default='commercial_regular', max_length=30, verbose_name='Тип лицензии'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/previews/', verbose_name='Превью (Скриншот/GIF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Краткое описание для карточки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='some_slug', max_length=255, unique=True, verbose_name='Слаг товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tech_stack',
            field=models.CharField(default='some-slug', max_length=255, verbose_name='Стек технологий (через запятую или как теги)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='some-description', verbose_name='Подробное описание / README'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название цифрового товара'),
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='Номер версии (например, 1.0.4)')),
                ('source_archive', models.FileField(upload_to='products/sources/%Y/%m/', verbose_name='Архив с кодом (.zip/.tar.gz)')),
                ('changelog', models.TextField(blank=True, null=True, verbose_name='Что нового в этой версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата релиза версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Версия продукта',
                'verbose_name_plural': 'Версии продуктов',
                'ordering': ['-created_at'],
            },
        ),
    ]
