# Generated by Django 5.2.15 on 2026-07-09 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_to_repository'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-created_at'], 'verbose_name': 'Репозиторий', 'verbose_name_plural': 'Репозитории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='category',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='stock',
        ),
        migrations.AddField(
            model_name='repository',
            name='categories',
            field=models.ManyToManyField(related_name='repositories', to='products.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_commercial_license',
            field=models.BooleanField(default=False, verbose_name='Коммерческая лицензия'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='repositories/', verbose_name='Фото репозитория'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название репозитория'),
        ),
    ]
